"""Gaussian random fields with a prescribed variogram.

Generated by circulant embedding: the covariance is evaluated on a grid of lags,
transformed, and used to colour white noise in the spectral domain. The field is
built on a domain twice the requested size and then cropped, which keeps the
wrap-around imposed by the FFT out of the region that is actually used.

This gives a synthetic aquifer whose true spatial statistics are known exactly,
so the variogram the pipeline fits from scattered points can be checked against
the value it was generated with.
"""

from __future__ import annotations

from typing import Optional, Tuple

import numpy as np

from gwpinn.stats.variogram import VariogramModel


def gaussian_random_field(
    shape: Tuple[int, int],
    cellsize: float,
    model: VariogramModel,
    rng: Optional[np.random.Generator] = None,
    mean: float = 0.0,
    pad: int = 2,
) -> np.ndarray:
    """A realisation with sill and range set by ``model``.

    Returns an array of ``shape`` whose mean is ``mean`` and whose sample
    variance matches ``model.sill``.
    """
    rng = rng or np.random.default_rng(0)
    ny, nx = shape
    my, nxx = pad * ny, pad * nx

    # Lag distance on the periodic embedding grid.
    dy = np.minimum(np.arange(my), my - np.arange(my)) * cellsize
    dx = np.minimum(np.arange(nxx), nxx - np.arange(nxx)) * cellsize
    r = np.hypot(dy[:, None], dx[None, :])

    cov = model.sill - model.gamma(r)
    spectrum = np.fft.fft2(cov).real
    spectrum = np.maximum(spectrum, 0.0)

    noise = rng.standard_normal((my, nxx))
    field = np.real(np.fft.ifft2(np.fft.fft2(noise) * np.sqrt(spectrum)))
    field = field[:ny, :nx]

    sd = field.std()
    if sd > 0:
        field = (field - field.mean()) / sd * np.sqrt(max(model.sill, 0.0))
    return mean + field


__all__ = ["gaussian_random_field"]
